version: 2

defaults: &defaults
  working_directory: ~/repo
jobs:
  test:
    docker:
    - image: circleci/node:8.9.1
    <<: *defaults  
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install  #install node.js package
      - run:
          name: run build
          command: npm build
      - run:
          name: Run tests
          command: npm test
          
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .

  deploy:
    orbs:
      heroku: circleci/heroku@1.0.0
    executor: heroku/machine #he basic buildpack-deps image, which has the prerequisites for installing heroku's CLI.
    steps:
      - checkout
      - heroku/install # Runs the heroku install command, if necessary.
      - heroku/deploy-via-git: # Deploys branch to Heroku via git push.
          - run: cd workshop-tonkotsu-nodejs
          - run: git checkout testbranch
          - run: heroku create
          - run: git remote rename heroku heroku-staging
          - run: git push heroku testbranch:master

          only-branch: testbranch
workflows:
  version: 2
  only_test:
    jobs:
      - test
      - deploy
      


