version: 2.1
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.9.1
orbs:
  heroku: circleci/heroku@0.0.8
workflows:
  heroku_deploy:
    jobs:
      - test
      - deploy
jobs:
  test:
    <<: *defaults  
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install  #install node.js package
      - run: npm build
      - run:
          name: Run tests
          command: npm test
          
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .

  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          parameters:
              app-name:
                description:
                  "The name of your Heroku App.
                  For backwards compatibility the literal value
                  `$HEROKU_APP_NAME` is the default, so you can
                  easily use this command by setting an environment
                  variable called HEROKU_APP_NAME"
                type: string
                default: $HEROKU_APP_NAME
              api-key:
                description:
                  "The API key to use. defaulting to the literal value $HEROKU_API_KEY, so you can
                  populate the environment variable HEROKU_API_KEY and not need to declare a value in code."
                type: string
                default: $HEROKU_API_KEY
          only-branch: deploybranch



